# Generated by Django 4.1.2 on 2022-10-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='trending',
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('BREAKING', 'BREAKING'), ('TRENDING', 'TRENDING')], max_length=255, null=True),
        ),
    ]
