# Generated by Django 4.1.2 on 2022-10-23 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_timezone_user_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezone',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
